server.port=8080
accounts.service.url=${ACCOUNTS_SERVICE_URL:http://localhost:28081}
catalog.service.url=${CATALOG_SERVICE_URL:http://localhost:28082}
ordering.service.url=${ORDERING_SERVICE_URL:http://localhost:28083}

management.endpoints.web.exposure.include=health

springdoc.api-docs.path=/api-docs
springdoc.swagger-ui.path=/swagger-ui.html
springdoc.packages-to-scan=io.github.doantrantuandat.example.gateway
springdoc.paths-to-match=/api/**,/actuator/**
