server.port=8080
accounts.service.url=${ACCOUNTS_SERVICE_URL:http://localhost:28081}
catalog.service.url=${CATALOG_SERVICE_URL:http://localhost:28082}

spring.datasource.url=jdbc:postgresql://${DB_HOST:localhost}:${DB_PORT:5432}/orderingdb?options=-c%20timezone%3DUTC
spring.datasource.username=crnk
spring.datasource.password=crnk
spring.jpa.hibernate.ddl-auto=update

crnk.jpa.exposeAll=true

management.endpoints.web.exposure.include=health

springdoc.api-docs.path=/api-docs
springdoc.swagger-ui.path=/swagger-ui.html
springdoc.packages-to-scan=io.github.doantrantuandat.example.ordering
